spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SpringBootZeroUltimate?reWriteBatchedInserts=true
    username: Mendax47
    password: Mendax47
    hikari:
      auto-commit: false
      maximum-pool-size: 100
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: update # TODO: NEED TO CHANGE THIS TO validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true # TODO: NEED TO TURN OFF IN PRODUCTION
#        format_sql: true # TODO: NEED TO TURN OFF IN PRODUCTION
#        use_sql_comments: true # TODO: NEED TO TURN OFF IN PRODUCTION
        generate_statistics: true # TODO: NEED TO TURN OFF IN PRODUCTION
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
          plan_cache_max_size: 8192